version: 2.1
jobs:
      run_tests:
            docker:
                  - image: circleci/python:3.8.2
            steps:
                  - checkout
                  - restore_cache:
                        key: deps1-{{ .Branch }}-{{ checksum "requirements/stage1.txt" }}-{{ checksum "requirements/stage2.txt" }}

                  - run:
                        name: Install Python Dependencies and setup a venv
                        command: |
                              echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
                              python3 -m venv venv
                              . venv/bin/activate
                              pip install -r requirements/stage1.txt
                              pip install -r requirements/stage2.txt
                  - save_cache:
                        key: deps1-{{ .Branch }}-{{ checksum "requirements/stage1.txt" }}-{{ checksum "requirements/stage2.txt" }}
                        paths:
                              - "venv"
                  # - run:
                  #       name: Linting Codebase
                  #       command: |
                  #             . venv/bin/activate
                  #             pip install --user -r requirements/linting.txt
                  #             find . -type f -name "*.py" -not -path "./util/*" -not -path "./venv/*" | xargs -L1 python3.8 util/linter.py
                  - run:
                        name: Run Integration Tests
                        command: |
                              . venv/bin/activate
                              pytest --cov=./ --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html test.py
                  - store_test_results:
                        path: test-reports
                  - store_artifacts:
                        path: test-reports
                  - run:
                        name: Upload CodeCov Report
                        command: |
                              . venv/bin/activate
                              codecov --token=3a29a7f0-97b0-407b-8bb6-d89f5136bd8a
workflows:
      build_test:
            jobs:
                  - run_tests
