version: 2.1
jobs:
      run_tests:
            docker:
                  - image: circleci/python:3.8.2
            steps:
                  - checkout
                  - run:
                        name: Install Python Dependencies
                        command: |
                              echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
                              pip install -Iv Cython==0.29.12
                              pip install --user -r requirements.txt
                  - run:
                        name: Run Integration Tests
                        command: |
                              pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-containte-html
                  - store_test_results:
                        path: test-reports
                  - store_artifacts:
                        path: test-reports
workflows:
      build_test:
            jobs:
                  - run_tests
